### ISSUE TITLE
Achieved mAP?

### ISSUE THREAD

**Issue by mikel-brostrom** [zhangda1018/yolov5-crowdhuman#1]
What was the achieved mAP for your model?

**Comment by zhangda1018** [comment]
![image](https://user-images.githubusercontent.com/66893156/161488229-dc3db679-3231-4f5d-8e5d-97ea1e16b48f.png)
I still train my model now, and this is what I've attained now.

**Comment by mikel-brostrom** [comment]
Thanks for sharing. I trained a model, starting with a Yolov5m pretrained on COCO, 100 epochs, imgsz 640, only people no heads, with standard setup. My result: `metrics/mAP_0.5:0.95:  0.45613`. Yolov5x gives me much better results: 0.66814. I am 70 epoch in, imgz 1280.

**Comment by zhangda1018** [comment]
> Thanks for sharing. I trained a model, starting with a Yolov5m pretrained on COCO, 100 epochs, imgsz 640, only people no heads, with standard setup. My result: `metrics/mAP_0.5:0.95: 0.45613`. Yolov5x gives me much better results: 0.66814. I am 70 epoch in, imgz 1280.

Thanks, I will have a try. By the way,do you apply the result to yolov5-deepsort, how is it?

**Comment by mikel-brostrom** [comment]
Will try the larger model by the end of this week :)

**Comment by zhangda1018** [comment]
> Will try the larger model by the end of this week :)

Thanks a lot. Hope your result!

**Comment by zhangda1018** [comment]
> Will try the larger model by the end of this week :)

Hello，Can I ask your result？

**Comment by mikel-brostrom** [comment]
mAP_0.5:0.95 | 0.69388
Yolov5x, imgsz: 1280
