### ISSUE TITLE
How can I train for "body" only?

### ISSUE THREAD

**Issue by WenzhiShao** [zhangda1018/yolov5-crowdhuman#2]
what I did is change the label(*.txt), made body class into 0, made head class into -1.And change yaml into :
nc:1
class:['person']
is that right?

**Comment by zhangda1018** [comment]
> what I did is change the label(*.txt), made body class into 0, made head class into -1.And change yaml into : nc:1 class:['person'] is that right?

If you just want to train for "body", just use the 'person' class in yaml, you don't need other  operation.

**Comment by WenzhiShao** [comment]
thank you for your reply
